name: Tests

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  formatting:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    env:
      HOST_TYPE: ci
      REDIS_QUEUE_HOST: redis
      REDIS_STATE_HOST: redis
    container:
      image: faasm/faabric-cli:0.0.15
    defaults:
      run:
        working-directory: /code/faabric
    services:
      redis:
        image: redis
    steps:
      # --- Code update ---
      - name: "Fetch ref"
        run: git fetch origin ${GITHUB_REF}:ci-branch
      - name: "Check out branch"
        run: git checkout --force ci-branch
      # --- Formatting checks ---
      - name: "Python formatting check"
        run: ./bin/check_python.sh
      - name: "Run C/C++ formatting"
        run: ./bin/run_clang_format.sh 
      - name: "Check C/C++ formatting changes"
        run: git diff --exit-code
      - name: "Run C/C++ linter"
        run: ./bin/run_clang_tidy.sh

  tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    env:
      HOST_TYPE: ci
      REDIS_QUEUE_HOST: redis
      REDIS_STATE_HOST: redis
    container:
      image: faasm/faabric-cli:0.0.15
    defaults:
      run:
        working-directory: /code/faabric
    services:
      redis:
        image: redis
    steps:
      # --- Code update ---
      - name: "Fetch ref"
        run: git fetch origin ${GITHUB_REF}:ci-branch
      - name: "Check out branch"
        run: git checkout --force ci-branch
      # --- Set-up ---
      - name: "Ping redis"
        run: redis-cli -h redis ping
      # --- Build ---
      - name: "Configure build"
        run: >
          cmake
          -GNinja
          -DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 
          -DCMAKE_C_COMPILER=/usr/bin/clang-10
          -DCMAKE_BUILD_TYPE=Release
          /code/faabric
        working-directory: /build/faabric
      - name: "Build tests"
        run: ninja faabric_tests
        working-directory: /build/faabric
      # --- Tests ---
      - name: "Run tests"
        run: ./bin/faabric_tests
        working-directory: /build/faabric
